---
abstract: 'A demonstration of various modulino ideas'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Modulino-Demo
no_index:
  directory:
    - t
requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
resources:
  repository: https://github.com/briandfoy/modulino-demo
version: 1.001
